server:
  port: 8010
  context-path: /
spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @profileActive@
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
# 关闭spring boot actuator的安全，否则敏感路径访问是401
management:
  security:
    enabled: false
