server:
  port: 8030
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  redis:
    host: ${spring.redis.host:localhost}
    password: ${spring.redis.password:123456}
    port: ${spring.redis.port:6379}
    timeout: ${spring.redis.timeout:0}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guandb_dyn_route?characterEncoding=utf8&useSSL=false
    username: ${spring.datasource.username:root}
    password: ${spring.datasource.password:root}
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      stat-view-servlet:
        allow:
eureka:
  client:
    serviceUrl:
      defaultZone: ${guandianbao.server.eureka.serviceUrl}
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
info:
  owner: zhoukj
  version: @project.version@
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log