server:
  port: 8080
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
info:
  owner: zhoukj
  version: @project.version@

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true
security: # 配置中心的用户名密码
  basic:
    enabled: ${guandianbao.security.basic.enabled:true}
  user:
    name: ${guandianbao.security.user.name:admin}
    password: ${guandianbao.security.user.password:admin}
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
