server:
  port: 7979
  tomcat:
    uri-encoding: UTF-8
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  redis:
    host: ${spring.redis.host:paascloud-db-redis}
    password: ${spring.redis.password:123456}
    port: ${spring.redis.port:6379}
    timeout: ${spring.redis.timeout:0}
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${guandianbao.server.eureka.serviceUrl}
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
      prefer-ip-address: true
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /v1/uac/**
      sensitiveHeaders:
      strip-prefix: true
      service-id: guandianbao-provider-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    uac2-route:
      path: /v2/uac/**
      sensitiveHeaders:
      strip-prefix: true
      service-id: guandianbao-provider-uac
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    promo-route:
      path: /v1/promo/**
      sensitiveHeaders:
      strip-prefix: true
      service-id: guandianbao-provider-promo
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true
info:
  owner: zhoukj
  version: @project.version@
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
guandianbao:
  enableSqlLogInterceptor: false