server:
  port: 7979
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  redis:
    host: ${spring.redis.host:127.0.0.1}
    password: ${spring.redis.password:123456}
    port: ${spring.redis.port:6379}
    timeout: ${spring.redis.timeout:0}

info:
  owner: zhoukj
  version: @project.version@
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
cldt:
  enableSqlLogInterceptor: false
