spring:
  profiles:
    active: dev
  rabbitmq:
    host: 47.96.173.142
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    password: guandbtest!@#
    port: 16379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
  mail:
    host: smtp.qq.com
    password: jtxhgopdrwcabbef
    port: 25
    username: 690590765
cldt:
  server:
    eureka:
      port: 8761
      hostname: localhost
      serviceUrl: http://root:root_dev@localhost:8761/eureka/
    discovery:
      port: 8080
      hostname: localhost
      serviceUrl: http://admin:admin@localhost:8080
    gateway:
      port: 80
      hostname: localhost
    monitor:
      port: 8010
      hostname: localhost
      serviceUrl: http://localhost:8010
    zipkin:
      port: 8020
      hostname: localhost
      serviceUrl: http://localhost:8020
    provider:
      ehc:
        port: 8040
        hostname: localhost
      mdc:
        port: 8030
        hostname: localhost
      omc:
        port: 8050
        hostname: localhost
      opc:
        port: 8070
        hostname: localhost
      ptc:
        port: 8060
        hostname: localhost
      uac:
        port: 8000
        hostname: localhost
    web:
      mall:
        port: 9000
        hostname: localhost
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120
  mail:
    host: 'smtp.qq.com'
    username: '690590765'
    password: 'gsglrwgeoyrhbcbd'
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          timeout: 2500
          starttls:
            enable: true
            required: true
  aliyun:
    key:
      accessKeyId: 'your aliyun accessKeyId'
      accessKeySecret: 'your aliyun accessKeySecret'
    rocketMq:
      namesrvAddr: 47.96.173.142:9876
    sms:
      signName: 快乐学习网
      regionId: cn-beijing
      endpoint:
      endpointName: cn-beijing
      product: 'your sms product'
      domain: dysmsapi.aliyuncs.com
  qiniu:
    key:
      accessKey: 'your qiniu accessKey'
      secretKey: 'your qiniu secretKey'
    oss:
      privateHost: 'your qiniu oss private host'
      publicHost: 'your qiniu oss public host'
  alipay:
    callback:
      url: http://dev-api.paascloud.net/omc/pay/alipayCallback
    qrCode:
      pcPath: E:/File/alipay/QRCode
      qiniuPath: alipay/QRCode/
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 0
  back:
    dubbo:
      registry:
        address: zookeeper://localhost:2181
        group: dubboservice/guandbService/dev-group
  swagger2:
    show: true
    