spring:
  boot:
    admin:
      client:
        metadata:
          user:
            name: ${security.user.name}
            password: ${security.user.password}
      monitor:
        period: 60000
      discovery:
        enabled: true
      notify:
        mail:
          to: 690590765@qq.com
          from: 690590765@qq.com
          enabled: true
      turbine:
        clusters: default
        location: CLDT-CLOUD-MONITOR 
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

security:
  user:
    name: admin
    password: admin_lcl
  basic:
    enabled: false
turbine:
  #收集监控信息的服务名
  app-config: CLDT-CLOUD-GATEWAY
  combine-host-port: true
  #集群名称
  cluster-name-expression: new String('default')